### ISSUE TITLE
is there automatic importing of indicies?

### ISSUE THREAD

**Issue by Slgoetz** [trendyminds/algolia#1]
I was playing around with this and couldn't see an easy way to import the data into Algolia.  Can you please let me know if there is an automated import  setup?

**Comment by aaronbushnell** [comment]
Hey @Slgoetz — this doesn't import any of your Craft data into Algolia, unfortunately. This is just a thin wrapper around Algolia's PHP library to so you can easily browse/search the data in your existing indices.
